// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AcceptFriendRequest(arg1:number):Promise<void>;

export function AddExperience(arg1:number):Promise<void>;

export function DeleteFriend(arg1:number):Promise<void>;

export function GetCurrentUser():Promise<any>;

export function GetFriends():Promise<any>;

export function GetMyRanking(arg1:string,arg2:number):Promise<any>;

export function GetTopRankings(arg1:string,arg2:number,arg3:number):Promise<any>;

export function GetUserByUID(arg1:number):Promise<any>;

export function Login(arg1:string,arg2:string):Promise<any>;

export function Logout():Promise<void>;

export function RefreshToken(arg1:string):Promise<any>;

export function RejectFriendRequest(arg1:number):Promise<void>;

export function SendFriendRequest(arg1:number):Promise<any>;

export function SetToken(arg1:string):Promise<void>;

export function VerifyTOTP(arg1:string,arg2:string):Promise<any>;
