// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AcceptFriendRequest(arg1:number):Promise<void>;

export function AddExperience(arg1:number):Promise<void>;

export function AddTeamMember(arg1:number,arg2:string,arg3:number):Promise<any>;

export function CreateTeam(arg1:string,arg2:string):Promise<any>;

export function DeleteFriend(arg1:number):Promise<void>;

export function DisbandTeam(arg1:number):Promise<void>;

export function GetCurrentUser():Promise<any>;

export function GetFriends():Promise<any>;

export function GetMatch(arg1:number):Promise<any>;

export function GetMyMatches(arg1:number,arg2:number):Promise<any>;

export function GetMyRanking(arg1:string,arg2:number):Promise<any>;

export function GetTeam(arg1:number):Promise<any>;

export function GetTeamMembers(arg1:number):Promise<any>;

export function GetTopRankings(arg1:string,arg2:number,arg3:number):Promise<any>;

export function GetUserByUUID(arg1:string):Promise<any>;

export function Login(arg1:string,arg2:string):Promise<any>;

export function Logout():Promise<void>;

export function RefreshToken(arg1:string):Promise<any>;

export function RejectFriendRequest(arg1:number):Promise<void>;

export function RemoveTeamMember(arg1:number,arg2:string):Promise<void>;

export function ReportMatchResult(arg1:models.TeamReportInput):Promise<any>;

export function SendFriendRequest(arg1:string):Promise<any>;

export function SetToken(arg1:string):Promise<void>;

export function UpdateMemberRole(arg1:number,arg2:string,arg3:number):Promise<void>;

export function VerifyTOTP(arg1:string,arg2:string):Promise<any>;
